export const mockWeatherData = {
  jakarta: {
    current: {
      tempC: 28,
      tempF: 82,
      condition: "Cerah Berawan",
      icon: "cloud-sun",
      location: "Jakarta, Indonesia",
      time: "10:30 AM",
      date: "Senin, 15 Okt 2026",
      humidity: 65,
      pressure: 1012,
      visibility: 10,
      windSpeed: 12,
      uvIndex: 5,
      dewPoint: 22,
    },
    hourly: [
      { time: "11:00", tempC: 29, tempF: 84, icon: "cloud-sun" },
      { time: "12:00", tempC: 31, tempF: 88, icon: "sun" },
      { time: "13:00", tempC: 32, tempF: 90, icon: "sun" },
      { time: "14:00", tempC: 31, tempF: 88, icon: "cloud-rain" },
      { time: "15:00", tempC: 29, tempF: 84, icon: "cloud-rain" },
      { time: "16:00", tempC: 28, tempF: 82, icon: "cloud" },
      { time: "17:00", tempC: 27, tempF: 80, icon: "cloud" },
      { time: "18:00", tempC: 26, tempF: 79, icon: "moon" },
    ],
    daily: [
      { day: "Hari Ini", maxC: 32, minC: 25, maxF: 90, minF: 77, condition: "Partly Cloudy", icon: "cloud-sun", morningC: 26, afternoonC: 32, eveningC: 27 },
      { day: "Selasa", maxC: 31, minC: 24, maxF: 88, minF: 75, condition: "Rain", icon: "cloud-rain", morningC: 25, afternoonC: 31, eveningC: 26 },
      { day: "Rabu", maxC: 30, minC: 24, maxF: 86, minF: 75, condition: "Thunderstorm", icon: "cloud-lightning", morningC: 24, afternoonC: 30, eveningC: 25 },
      { day: "Kamis", maxC: 33, minC: 25, maxF: 91, minF: 77, condition: "Sunny", icon: "sun", morningC: 26, afternoonC: 33, eveningC: 28 },
      { day: "Jumat", maxC: 32, minC: 26, maxF: 90, minF: 79, condition: "Partly Cloudy", icon: "cloud-sun", morningC: 27, afternoonC: 32, eveningC: 27 },
    ],
  },
  tokyo: {
    current: {
      tempC: 15,
      tempF: 59,
      condition: "Hujan Gerimis",
      icon: "cloud-rain",
      location: "Tokyo, Japan",
      time: "12:30 PM",
      date: "Senin, 15 Okt 2026",
      humidity: 80,
      pressure: 1008,
      visibility: 5,
      windSpeed: 20,
      uvIndex: 2,
      dewPoint: 12,
    },
    hourly: [
      { time: "13:00", tempC: 14, tempF: 57, icon: "cloud-rain" },
      { time: "14:00", tempC: 14, tempF: 57, icon: "cloud-rain" },
      { time: "15:00", tempC: 13, tempF: 55, icon: "cloud" },
      { time: "16:00", tempC: 13, tempF: 55, icon: "cloud" },
      { time: "17:00", tempC: 12, tempF: 54, icon: "cloud" },
      { time: "18:00", tempC: 11, tempF: 52, icon: "moon" },
      { time: "19:00", tempC: 11, tempF: 52, icon: "moon" },
      { time: "20:00", tempC: 10, tempF: 50, icon: "moon" },
    ],
    daily: [
      { day: "Hari Ini", maxC: 16, minC: 10, maxF: 61, minF: 50, condition: "Rain", icon: "cloud-rain", morningC: 12, afternoonC: 16, eveningC: 11 },
      { day: "Selasa", maxC: 18, minC: 12, maxF: 64, minF: 54, condition: "Cloudy", icon: "cloud", morningC: 14, afternoonC: 18, eveningC: 13 },
      { day: "Rabu", maxC: 20, minC: 14, maxF: 68, minF: 57, condition: "Sunny", icon: "sun", morningC: 15, afternoonC: 20, eveningC: 15 },
      { day: "Kamis", maxC: 22, minC: 15, maxF: 72, minF: 59, condition: "Partly Cloudy", icon: "cloud-sun", morningC: 17, afternoonC: 22, eveningC: 16 },
      { day: "Jumat", maxC: 21, minC: 14, maxF: 70, minF: 57, condition: "Rain", icon: "cloud-rain", morningC: 16, afternoonC: 21, eveningC: 15 },
    ],
  },
  london: {
    current: {
      tempC: 8,
      tempF: 46,
      condition: "Berkabut",
      icon: "cloud-fog",
      location: "London, UK",
      time: "04:30 AM",
      date: "Senin, 15 Okt 2026",
      humidity: 90,
      pressure: 1020,
      visibility: 2,
      windSpeed: 5,
      uvIndex: 1,
      dewPoint: 6,
    },
    hourly: [
      { time: "05:00", tempC: 7, tempF: 45, icon: "cloud-fog" },
      { time: "06:00", tempC: 7, tempF: 45, icon: "cloud-fog" },
      { time: "07:00", tempC: 8, tempF: 46, icon: "cloud" },
      { time: "08:00", tempC: 9, tempF: 48, icon: "cloud" },
      { time: "09:00", tempC: 10, tempF: 50, icon: "cloud-sun" },
      { time: "10:00", tempC: 12, tempF: 54, icon: "cloud-sun" },
      { time: "11:00", tempC: 13, tempF: 55, icon: "sun" },
      { time: "12:00", tempC: 14, tempF: 57, icon: "sun" },
    ],
    daily: [
      { day: "Hari Ini", maxC: 14, minC: 6, maxF: 57, minF: 43, condition: "Foggy to Sunny", icon: "cloud-sun", morningC: 9, afternoonC: 14, eveningC: 10 },
      { day: "Selasa", maxC: 12, minC: 5, maxF: 54, minF: 41, condition: "Rain", icon: "cloud-rain", morningC: 7, afternoonC: 12, eveningC: 8 },
      { day: "Rabu", maxC: 10, minC: 3, maxF: 50, minF: 37, condition: "Cloudy", icon: "cloud", morningC: 5, afternoonC: 10, eveningC: 6 },
      { day: "Kamis", maxC: 11, minC: 4, maxF: 52, minF: 39, condition: "Partly Cloudy", icon: "cloud-sun", morningC: 6, afternoonC: 11, eveningC: 7 },
      { day: "Jumat", maxC: 9, minC: 2, maxF: 48, minF: 36, condition: "Rain", icon: "cloud-rain", morningC: 4, afternoonC: 9, eveningC: 5 },
    ],
  }
};

export const mockFavorites = [
  { id: "jakarta", city: "Jakarta", country: "Indonesia", temp: 28, condition: "Cerah Berawan", icon: "cloud-sun" },
  { id: "tokyo", city: "Tokyo", country: "Japan", temp: 15, condition: "Hujan Gerimis", icon: "cloud-rain" },
  { id: "london", city: "London", country: "UK", temp: 8, condition: "Berkabut", icon: "cloud-fog" },
];
